// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOZEp85uRHjkHKAvhvRg6AHfQyXq_1CIs',
    appId: '1:320896942129:web:5f774c83bd294d63b99510',
    messagingSenderId: '320896942129',
    projectId: 'expense-tracker-9dc30',
    authDomain: 'expense-tracker-9dc30.firebaseapp.com',
    storageBucket: 'expense-tracker-9dc30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSrzfYgMZVSkTFObEpeKsMa9nchTvqMRE',
    appId: '1:320896942129:android:20cb8fc8ca241c40b99510',
    messagingSenderId: '320896942129',
    projectId: 'expense-tracker-9dc30',
    storageBucket: 'expense-tracker-9dc30.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOZEp85uRHjkHKAvhvRg6AHfQyXq_1CIs',
    appId: '1:320896942129:web:c77b2944980ddcf3b99510',
    messagingSenderId: '320896942129',
    projectId: 'expense-tracker-9dc30',
    authDomain: 'expense-tracker-9dc30.firebaseapp.com',
    storageBucket: 'expense-tracker-9dc30.firebasestorage.app',
  );
}
